### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by imycod** [fi3ework/vscode-antd-rush#51]
我的vscode不提示,只提示const Table:any;

![1612969529(1)](https://user-images.githubusercontent.com/59326563/107528388-bbb00780-6bf4-11eb-984e-729de3bc4452.jpg)

![1612969561(1)](https://user-images.githubusercontent.com/59326563/107528432-c8346000-6bf4-11eb-91f8-5d7c50ed7a06.jpg)

**Comment by fi3ework** [comment]
依赖里只有 `@types/react` 没有 antd 吗
